import React,{useContext} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from "next/router";
import Feed from "../components/Feed.js";
import { AuthContext } from '../context/auth.js';
export default function Home() {

  const {user}=useContext(AuthContext);

  const Redirect=()=>{
      const router=useRouter()
      router.push("/login");
      return null;
  }

  return (

    <div>
      <Head>
        <title>Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        user?.uid? <Feed />:<Redirect/>
      }
   

      
    </div>
  )
}
